// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZiaLTHdwr5p7t7ftUkLZsX5L4_si46TI',
    appId: '1:104086055461:web:d28541697bb6df42c2edcc',
    messagingSenderId: '104086055461',
    projectId: 'last-fca00',
    authDomain: 'last-fca00.firebaseapp.com',
    storageBucket: 'last-fca00.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXYgWuLqW97TS-ypnSGJQnTW-Mc8YR0Ys',
    appId: '1:104086055461:android:0c985f9dc4770dddc2edcc',
    messagingSenderId: '104086055461',
    projectId: 'last-fca00',
    storageBucket: 'last-fca00.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZiaLTHdwr5p7t7ftUkLZsX5L4_si46TI',
    appId: '1:104086055461:web:33058c1883f3d438c2edcc',
    messagingSenderId: '104086055461',
    projectId: 'last-fca00',
    authDomain: 'last-fca00.firebaseapp.com',
    storageBucket: 'last-fca00.firebasestorage.app',
  );
}
