// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhLqrRe0rgJwUdtcYoic2KTPiYNBwxl8',
    appId: '1:496484225465:web:30558bfc58363496dce668',
    messagingSenderId: '496484225465',
    projectId: 'imagetotext-a8823',
    authDomain: 'imagetotext-a8823.firebaseapp.com',
    storageBucket: 'imagetotext-a8823.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClE9PiraIIm2uceAiQ3ejaUotu6jPoeK4',
    appId: '1:496484225465:android:43f2a5fffb49202bdce668',
    messagingSenderId: '496484225465',
    projectId: 'imagetotext-a8823',
    storageBucket: 'imagetotext-a8823.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPhLqrRe0rgJwUdtcYoic2KTPiYNBwxl8',
    appId: '1:496484225465:web:cb097a77f4969113dce668',
    messagingSenderId: '496484225465',
    projectId: 'imagetotext-a8823',
    authDomain: 'imagetotext-a8823.firebaseapp.com',
    storageBucket: 'imagetotext-a8823.firebasestorage.app',
  );
}
